### ISSUE TITLE
Bundle size

### ISSUE THREAD

**Issue by benjaminjt** [sindresorhus/decamelize#12]
The new dependency on `xregexp` (added in 35e7cff91ca8212c34a125d858b06fa41d6cce58) has changed the bundle size by 2 orders of magnitude: https://bundlephobia.com/result?p=decamelize@2.0.0

Was this intentional?

**Comment by sindresorhus** [comment]
I mainly target Node.js so bundle size is not a big concern unless it becomes extreme. Unicode support is very useful, and expected behavior today, and there's not really any other easy way of achieving that at the moment than using `xregexp`. As per https://github.com/sindresorhus/decamelize/pull/11#issuecomment-356061779, in the future, we'll hopefully be able to remove it in favor of the native `u` regex flag.

**Comment by joscha** [comment]
> unless it becomes extreme

fair enough. From a browser target perspective I thin the jump from 236 bytes in `1.2.0` (see https://bundlephobia.com/result?p=decamelize@1.2.0) to 29.3KB in `2.0.0` (see https://bundlephobia.com/result?p=decamelize@2.0.0) would be considered extreme for a simple package like that, I think. In that case people might want to consider staying on `1.2.0` if they don't need unicode support.

**Comment by benjaminjt** [comment]
Thanks for the reply @sindresorhus
