### ISSUE TITLE
Decamelizing a capitalized word gives odd results

### ISSUE THREAD

**Issue by JanStevens** [sindresorhus/decamelize#21]
Hello,

When decamelizing an upcase word one gets odd results like this:

```js
decamelize('ADDRESS1') === 'addres_s1'
```

Not sure what the logic is in it but I would expect that it returns `address1`

Regards

**Comment by sindresorhus** [comment]
Yes, that's a bug.

**Comment by coreyfarrell** [comment]
This is due to the handling of acronyms, `$2` of the second regular express is `S1`.  This specific example could be fixed without breaking any existing tests by removing the `\d` match from the second regular expression.

I just submitted a patch to drop xregexp, if you'd like I can submit a follow-up to remove the `\d` from the pattern.  Probably makes sense to do it as part of the semver-major just in case it is breaking to anyone?

**Comment by sindresorhus** [comment]
> if you'd like I can submit a follow-up to remove the \d from the pattern. Probably makes sense to do it as part of the semver-major just in case it is breaking to anyone?

👍 That would be great.
